feign:
  client:
    config:
      - Authorization-Client:
          connectTimeout: 10000
          readTimeout: 10000

ayay:
  services:
    authorization-client: http://localhost:10000

spring:
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: http://authorization
          Predicates: Path=/api/v*/authorization/**
          filters:
            - AuthFilter
        - id: account
          uri: http://account
          Predicates: Path=/api/v*/account/**
